name: build
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
    build:
        runs-on: ubuntu-22.04
        permissions:
          contents: read
          packages: write    
        steps:
          - uses: actions/checkout@v4
    
          - name: Log into registry ${{ env.REGISTRY }}
            uses: docker/login-action@v2
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Setup Docker buildx
            uses: docker/setup-buildx-action@v3
    
          - name: Build and push container image
            uses: docker/bake-action@v6
            with:
                source: .
                push: true